source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'
use_frameworks!

target 'Promis_Example' do
  pod 'Promis', :path => '../'

  target 'Promis_Tests' do
    inherit! :search_paths

    
  end
end
