# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

default_platform :ios

platform :ios do

  before_all do
    $codecov_token = ENV['CODE_COV_TOKEN']
    $pod_name = ENV['POD_NAME']
  end

  desc "Run the unit tests"
  lane :unit_tests do
    scan(
      scheme: "#{$pod_name}-Example",
      workspace: "./Example/#{$pod_name}.xcworkspace"
      )
  end

  desc "Submit the code coverage to codecov.io"
  lane :submit_code_coverage do
    sh "slather coverage --cobertura-xml --verbose --output-directory ./code_coverage --scheme #{$pod_name}-Example --binary-basename #{$pod_name} --workspace ./Example/#{$pod_name}.xcworkspace ./Example/#{$pod_name}.xcodeproj"
    sh "bash <(curl -s https://codecov.io/bash) -f ./code_coverage/cobertura.xml -X coveragepy -X gcov -X xcode -t #{$codecov_token}"
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer